name: Daily Site Publication

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check-out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}

      - name: Install mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3

      - name: Run reads script
        run: mise run reads
        env:
          READWISE_KEY: ${{ secrets.READWISE_KEY }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Published on $(date +"%Y-%m-%d %H:%M")
          file_pattern: 'content/reads.md'
